#! /usr/bin/env bash

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

WORK_DIRECTORY=~/workspace/

if [[ $(uname) == "Darwin" ]] && [[ -d ~/workspace ]]; then
    WORK_DIRECTORY=~/workspace
elif [[ -d /c/workspace ]]; then
    WORK_DIRECTORY=/c/workspace
fi

alias cdw="cd /c/workspace/"

# global named directory, usage `cd ~w`
hash -d w="${WORK_DIRECTORY}/"
hash -d df=~/.dotfiles

