#! /usr/bin/env bash

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# cd hook
function chpwd {
    # NODE VERSION
    file=$(find . \( -name ".nvmrc" -o -name ".nodeversion" \) -maxdepth 1 | head -n1)
    if [[ -f $file ]]; then
        ver=$(cat $file)
        curr=$(node -v 2>/dev/null)
        printf '%-12s %-16s\n' "Required node " "$ver"
        printf '%-12s %-16s\n' "Current " "$curr"
    fi
    # END NODE VERSION
}

WORK_DIRECTORY=~/workspace/

if [[ $(uname) == "Darwin" ]] && [[ -d ~/workspace ]]; then
    WORK_DIRECTORY=~/workspace
elif [[ -d /c/workspace ]]; then
    WORK_DIRECTORY=/c/workspace
fi

alias cdw="cd ${WORK_DIRECTORY}"

# global named directory, usage `cd ~w`
hash -d w="${WORK_DIRECTORY}/"
hash -d df=~/.dotfiles

